version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true

image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
    - nuget restore

build:
  publish_nuget: true
  include_nuget_references: true
  publish_nuget_symbols: true
  verbosity: minimal

before_package:
- cmd: nuget pack Deploy/Phi.Kafka.Fluent.nuspec -Version %APPVEYOR_BUILD_VERSION%
- cmd: nuget pack Deploy/Phi.Kafka.Active.nuspec -Version %APPVEYOR_BUILD_VERSION%
- cmd: nuget pack Deploy/Phi.Kafka.Fluent.Active.nuspec -Version %APPVEYOR_BUILD_VERSION%

artifacts:
- path: /.\*.nupkg/
  name: Nuget Package

deploy:
- provider: NuGet
  api_key:
    secure: ykxmIGM1+4Q1l8cel1oh6PJQhKiUyiAd4/4U99eekSlUWyaQEyPG45r6++BKe0hM